### ISSUE TITLE
multi_gpu_model InvalidArgumentError on seq2seq model

### ISSUE THREAD

**Issue by andreynikk** [keras-team/keras#11024]
Hi,

I'm running a seq2seq model using GRU's on 8 GPUs, using fit_generator and this is the error I'm having:
InvalidArgumentError: Incompatible shapes: [128,100] vs. [1024,100]
	 [[Node: replica_0/model_1/gru_1/while/add = Add[T=DT_FLOAT, _class=["loc:@train.../Reshape_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](replica_0/model_1/gru_1/while/BiasAdd, replica_0/model_1/gru_1/while/MatMul_3)]]
	 [[Node: replica_0/model_1/gru_2/while/Identity/_967 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7766_replica_0/model_1/gru_2/while/Identity", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopreplica_0/model_1/gru_2/while/TensorArrayReadV3_1/_133)]]

keras was installed from master directly and updated to latest tensorflow-gpu from pip.

the generator is designed to yield a batch of 1024 so each GPU would work on a batch of 128.
if I reduce for example the number of GPUs to 4, I would have the following error:
InvalidArgumentError: Incompatible shapes: [256,100] vs. [1024,100]

for going over similar issues I've found the following issue #9449 and the merge request #10845 saying the issue is fixed. I've installed keras from source and I still have the issue.

Is it possible the issue is not fixed for GRUs?

this is my model definition:
word_input = Input(shape=(word_dim,))
decoder_inputs = Input(shape=(None,))
decoder_embed = Embedding(input_dim=num_tokens, output_dim=word_dim)
decoder_gru = GRU(word_dim, return_sequences=True, return_state=True)
decoder_dense = Dense(num_tokens, activation='softmax')

embedded = decoder_embed(decoder_inputs)
gru_output, state_h = decoder_gru(embedded, initial_state=word_input)
decoder_outputs = decoder_dense(gru_output)

model = Model([word_input, decoder_inputs], decoder_outputs)

rmsprop = optimizers.RMSprop(lr=0.001)

parallel_model = multi_gpu_model(model, gpus=8)
parallel_model.compile(loss='categorical_crossentropy',optimizer=rmsprop,metrics=['acc'])

filename = 'model.h5'
checkpoint = ModelCheckpoint(filename, monitor='loss', verbose=1, save_best_only=True, mode='min')

parallel_model.fit_generator(data_generator.generate(), training_size//batch_size*num_steps, num_epochs, callbacks=[checkpoint], verbose=1)

Thanks!

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by yanboliang** [comment]
@andreynikk I'm sure this is fixed for all ```RNN``` layers including ```GRU```. Please check your environment and the keras version you run, if there are multiple keras installed, it may run into other versions. You can try ```pip uninstall keras``` to uninstall it and then use ```python setup.py install``` to install the master version. If there is still errors, please let me know.

**Comment by andreynikk** [comment]
Hi @yanboliang 

I did what you requested just to be on the safe side:
print(tf.__version__)
print(keras.__version__)
1.10.1
2.2.2

Its either the issue was not fixed on GRUs or the way I combine multi_gpu_model with a generator (through fit_generator) is wrong.
the main hint on the issue would be in the error output:
InvalidArgumentError: Incompatible shapes: [32,100] vs. [256,100]

some more context: my generator yields batches of [256,100] (tested and verified), and from official documentation multi_gpu_model would split the provided batch to the number of GPUs, so that for a batch of [256,100] I get [32,100] batch size for each GPU, and this is the exact error I'm having.
so could be that it is unable to split properly the incoming batch from a generator to sub-batches that will accompany each GPU?

my model definitions:
rmsprop = optimizers.RMSprop(lr=1)
parallel_model = multi_gpu_model(model, gpus=8)
parallel_model.compile(loss='categorical_crossentropy',optimizer=rmsprop,metrics=['acc'])
checkpoint = ModelCheckpoint(filename, monitor='loss', verbose=1, save_best_only=True, mode='min')
parallel_model.fit_generator(data_generator.generate(), training_size//batch_size, num_epochs,
                    callbacks=[checkpoint], verbose=1)

If you need any more information please let me know.

**Comment by thiziri** [comment]
I have the same problem, my model is working well on CPUs but raises the same error you mentioned above, error with GPUs.
Any help, please?

**Comment by yanboliang** [comment]
@andreynikk Can you share the minimal code snippet which can reproduce this error? I still can't reproduce this issue on my environment which has two GPUs. If you can share the code, I can help to debug.
