### ISSUE TITLE
Warnings after TensorFlow and Keras update.

### ISSUE THREAD

**Issue by kiflowb777** [keras-team/keras#13326]
**System information**  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14
- Keras version:  2.2.5
- Python version:  3.6.1
- CUDA/cuDNN version:  7.5.0
- GPU model and memory:  RTX 2060

After update TensorFlow (1.13.1 to 1.14) 
I receive the following warnings:

```
WARNING From C:\python\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.
        tensorflow:119		
```
		
```
WARNING:tensorflow:From C:\python\lib\site-packages\keras\backend\tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.
```

```
WARNING From C:\python\lib\site-packages\keras\backend\tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.
        tensorflow:119		
```
		
```
WARNING:tensorflow:From C:\python\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
```

```
`WARNING:tensorflow:From C:\python\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.
`
```

```
WARNING From C:\python\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.
        tensorflow:119
```
		
```
WARNING C:\python\lib\site-packages\keras\utils\data_utils.py:651: DeprecationWarning: `wait_time` is not used anymore.
  DeprecationWarning)
        py.warnings:99
```
		
```
WARNING C:\python\lib\site-packages\keras\preprocessing\image.py:43: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  if 'dtype' in inspect.getargspec(image.img_to_array).args:
        py.warnings:99
```
		
		
```
WARNING C:\python\lib\site-packages\keras\preprocessing\image.py:43: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  if 'dtype' in inspect.getargspec(image.img_to_array).args:
        py.warnings:99
```

**Comment by fchollet** [comment]
Thank you for the report. Some of these issues are with `keras-preprocessing` (the last 3). @Dref360 could you please take a look at the last 3?

**Comment by Dref360** [comment]
I think this is fixed in the most recent release. Please update keras-preprocessing.

**Comment by kiflowb777** [comment]
Thanks you. After updating the keras-preprocessing the last 2 warnings have disappeared.

**Comment by JxSrcInc** [comment]
after "pip install --upgrade keras-preprocessing" on windows 10, still see WARNING From C:\python\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

**Comment by AKS-IS** [comment]
> after "pip install --upgrade keras-preprocessing" on windows 10, still see WARNING From C:\python\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Did you find a solution?
