### ISSUE TITLE
ValueError: Arguments and signature arguments do not match. got: 13, expected: 14 

### ISSUE THREAD

**Issue by cmp1** [keras-team/keras#13597]
**System information**  
- Have I written custom code (as opposed to using example directory):  

Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
Windows 10

- TensorFlow backend (yes / no):

Yes
  
- TensorFlow version:  

2.0

- Keras version:  

2.3.1

- Python version:  

3.7

- CUDA/cuDNN version:  

None - CPU only

**Describe the current behavior**  

I am attempting to generate confidence intervals using dropout as per logic in [here](https://medium.com/hal24k-techblog/how-to-generate-neural-network-confidence-intervals-with-keras-e4c0b78ebbdf) 

unfortunately I keep receiving (now) the error above?

```

     53 
     54 for i in range(num_iter):
---> 55     result[i, :] = predict_with_dropout(input_data+[1])[0]

c:\users\cprice2\appdata\local\continuum\envs\tf_new\lib\site-packages\tensorflow_core\python\keras\backend.py in __call__(self, inputs)
   3738         value = math_ops.cast(value, tensor.dtype)
   3739       converted_inputs.append(value)
-> 3740     outputs = self._graph_fn(*converted_inputs)
   3741 
   3742     # EagerTensor.numpy() will often make a copy to ensure memory safety.

c:\users\cprice2\appdata\local\continuum\envs\tf_new\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   1079       TypeError: For invalid positional/keyword argument combinations.
   1080     """
-> 1081     return self._call_impl(args, kwargs)
   1082 
   1083   def _call_impl(self, args, kwargs, cancellation_manager=None):

c:\users\cprice2\appdata\local\continuum\envs\tf_new\lib\site-packages\tensorflow_core\python\eager\function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1119       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
   1120           list(kwargs.keys()), list(self._arg_keywords)))
-> 1121     return self._call_flat(args, self.captured_inputs, cancellation_manager)
   1122 
   1123   def _filtered_call(self, args, kwargs):

c:\users\cprice2\appdata\local\continuum\envs\tf_new\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1222     if executing_eagerly:
   1223       flat_outputs = forward_function.call(
-> 1224           ctx, args, cancellation_manager=cancellation_manager)
   1225     else:
   1226       gradient_name = self._delayed_rewrite_functions.register()

c:\users\cprice2\appdata\local\continuum\envs\tf_new\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    491           "Arguments and signature arguments do not match. "
    492           "got: %s, expected: %s " %
--> 493           (len(args), len(list(self.signature.input_arg))))
    494 
    495     function_call_options = ctx.function_call_options

ValueError: Arguments and signature arguments do not match. got: 13, expected: 14 
```
**Describe the expected behavior**  

Expect a new model to be initialised from the saved config.

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

```
# Model
def mlp_model():
  model = tf.keras.Sequential([   
    tf.keras.layers.Dense(3, input_dim = 3,
                          kernel_initializer = 'glorot_uniform',
                          activation = 'elu'),
    tf.keras.layers.Dense(160, 
                          activation = 'elu', 
                          kernel_regularizer = regularizers.l2(0.001)),                     
    tf.keras.layers.GaussianNoise(0.3),  
    tf.keras.layers.Dense(160, 
                          activation = 'elu',
                          kernel_regularizer = regularizers.l2(0.003)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(160, 
                          activation = 'elu',
                          kernel_regularizer = regularizers.l2(0.003)),                                               
    tf.keras.layers.Dense(160, 
                          activation = 'relu',
                          kernel_regularizer = regularizers.l2(0.004)), #128 for unscaled
    tf.keras.layers.Dense(1) 
  ])

  model.compile(optimizer = opt, 
                loss = root_mean_squared_error,
                metrics=['mean_squared_error', 
                         'mean_absolute_error',
                         root_mean_squared_error])
  return model

# fit model
model = mlp_model()
model_history = model.fit(train_batch, 
                          validation_data = test_batch,
                          epochs = 100,
                          shuffle = False,
                          callbacks = [early_stop, 
                                       model_checkpoint,
                                       tensorboard_callback])

# Create dropout func 
def create_dropout_predict_function(model, dropout):

    # Load the config of the original model
    conf = model.get_config()

    # Add the specified dropout to all layers
    for layer in conf['layers']:
        # Dropout layers
        if layer["class_name"]=="Dropout":
            layer["config"]["rate"] = dropout

    # Using Functional API
    model_dropout = tf.keras.Sequential.from_config(conf)
    model_dropout.set_weights(model.get_weights()) 

    # Predict with dropout
    predict_with_dropout = K.function(model_dropout.inputs+[K.learning_phase()], model_dropout.outputs)

    return predict_with_dropout

# Create predictions with dropout

# input data
input_data = np.array(forecast_df)

# configure dropout, number of iterations
dropout = 0.5
num_iter = 20
num_samples = input_data[0].shape[0]

predict_with_dropout = create_dropout_predict_function(model, dropout)

predictions = np.zeros((num_samples, num_iter))

for i in range(num_iter):
    predictions[:, i] = predict_with_dropout(input_data+[1])[0].reshape(-1)

```

Adding a note in to mention that my train/test/forecast data is generated via tf.data.Dataset:

````
train_data = tf.data.Dataset.from_tensor_slices((X_train.values, y_train.values))
test_data = tf.data.Dataset.from_tensor_slices((X_test.values, y_test.values))
forecast_data = tf.data.Dataset.from_tensor_slices((forecast_ahead_df.values))
```


Thank you for your help!

**Comment by claeszacho** [comment]
I have the same issue, using the fit_generator

**Comment by claeszacho** [comment]
I've fixed my issue by specifying target data (y) for both test and validation data.

**Comment by Unimax** [comment]
still getting similar issue 
` self.agent_model.model.predict_on_batch(data)`
ValueError: Arguments and signature arguments do not match. got: 92, expected: 93 
@claeszacho can u explain your solution a bit.

**Comment by claeszacho** [comment]
Using the fit_generator, I kept getting this issue when only specifying X data for both the training data and validation data. Since I'm working with unlabelled sequential data in an unsupervised training situation, I just set the same data for both X and Y in both the training and validation data.

I could be a bit of a hack, and an incorrect way of doing things - I'm not sure, but my issue is gone and the results has been fine.

I can't really tell for the example above, how `train_batch` is configured, but my guess will be that the fitting call should be changed to something like this.
`
model_history = model.fit(x=train_batch, y=train_batch 
                          validation_data = (test_batch, train_batch)
                          epochs = 100,
                          shuffle = False,
                          callbacks = [early_stop, 
                                       model_checkpoint,
                                       tensorboard_callback])
`

**Comment by ahmedbr** [comment]
I'm having a similar problem:

`  File "/project_path/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/project_path/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/project_path/venv/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/project_path/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/project_path/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/project_path/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/project_path/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/project_path/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/project_path/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 527, in call
    (len(args), len(list(self.signature.input_arg))))
ValueError: Arguments and signature arguments do not match. got: 37, expected: 39 
`
And this is the error line:

`            model.fit_generator(generator=batch_generator(X_train, y_train, batch_size, True), epochs=1,
                                steps_per_epoch=np_steps),
                                verbose=1,
                                validation_data=batch_generator(X_valid, y_valid, batch_size, False),
                                validation_steps=np_steps)`

Using:

- Tensorflow-gpu: 2.0.1
- Keras: 2.3.1
- Ubuntu: 18.04 LTS

**Comment by claeszacho** [comment]
@ahmedbr The function ```batch_generator``` you're calling - is that a custom function, or is it part of the Keras? I'm not familiar..

**Comment by ahmedbr** [comment]
> @ahmedbr The function `batch_generator` you're calling inside the `fit_generator` - is that a custom function, or is it part of the Keras? I'm not familiar..

Sorry for late reply. No it's custom function. The code snippet is available here: https://www.kaggle.com/c/talkingdata-mobile-user-demographics/discussion/22567

**Comment by claeszacho** [comment]
@ahmedbr Can you check the shape for the X and Y values that ```batch_generator``` are yielding? My guess is that your issue is introduced due to some misalignment between the output shape of the different x/y sets. Either in the training data, validation data or between those two. But I'm not entirely sure.

**Comment by ahmedbr** [comment]
@claeszacho thanks for your suggestion but to me the problem doesn't seem to be related to X and y shapes. I re-run as following and still have the issue:

```
model.fit_generator(generator=batch_generator(X_train, y_train, divide_on, True), epochs=1,
                                steps_per_epoch=np_steps,
                                verbose=1)
```

```
def batch_generator(X, y, batch_size, shuffle):
    number_of_batches = round(X.shape[0] / batch_size)
    print(f'y.shape: {X.shape}')
    print(f'X.shape[0]: {X.shape[0]}')
    print(f'batch_size: {batch_size}')
    print(f'number_of_batches: {number_of_batches}')
    counter = 0
    sample_index = np.arange(X.shape[0])
    if shuffle:
        np.random.shuffle(sample_index)
    while True:
        batch_index = sample_index[batch_size * counter:batch_size * (counter + 1)]
        print(f'counter: {counter}')
        print(f'batch_index: {batch_index}')
        X_batch = X[batch_index, :].toarray()
        y_batch = y[batch_index]
        counter += 1
        print(f'yielded X_batch shape: {X_batch.shape} where counter: {counter}')
        print(f'yielded y_batch shape: {y_batch.shape} where counter: {counter}')
        yield X_batch, y_batch
        if counter == number_of_batches:
            if shuffle:
                np.random.shuffle(sample_index)
            counter = 0
```
While the result is:

```
shape of x_train: (1407577, 207)
shape of x_valid: (74084, 207)
Epoch 1/1
y.shape: (1407577, 207)
X.shape[0]: 1407577
batch_size: 64
number_of_batches: 21993
counter: 0
batch_index: [  55578  885043  826530 1085983  596906  990879  150577  916018 1283648
  657662   22295  978107 1330422 1094582 1323311 1386819 1349709  361209
 1314015  112607 1363984  179845  464715  474078  337839 1097602 1173681
  910575 1113526   27510  647144 1081263  678677  567365  149537  936813
  202732  727397   21943  563727  923775  661254  465769  383644   99391
  918760 1152295   23548  511531  661704  590537  855781  654484 1008951
  690456  414501  998788   97076  334435   57625  822775  125039  857771
 1103476]
yielded X_batch shape: (64, 207) where counter: 1
yielded y_batch shape: (64, 1) where counter: 1
counter: 1
batch_index: [ 784817  248893  472646 1010253 1400872  522094  217448 1120737  844047
  837030 1298761  768817  728090  799502  951408 1356634  365863  997856
  752368  558098  732175  571739 1048726  536754 1315847 1032336  413975
  366115  550960  976257 1116407  237934  386406 1160910  113013  163694
  437774  372660 1164205  335589  223032 1364559  626345 1135905  396354
 1120329  567954 1252556  763024  351094  445536  734038 1344405  239830
  869035  728995  288278  238975  699285 1267507  131834   24448  233283
  623641]
Traceback (most recent call last):
  File "mlp.py", line 443, in <module>
yielded X_batch shape: (64, 207) where counter: 2
yielded y_batch shape: (64, 1) where counter: 2
    main()
  File "mlp.py", line 371, in main
    model1 = run_model1(X_train, y_train, X_valid, y_valid)
  File "mlp.py", line 255, in run_model1
    verbose=1)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/media/ahmed/DATA/projects/TradeValley/price_anomaly_detection/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 527, in call
    (len(args), len(list(self.signature.input_arg))))
ValueError: Arguments and signature arguments do not match. got: 37, expected: 39 

```

It fails in the second iteration of the loop.

**Comment by ahmedbr** [comment]
@claeszacho thanks for your suggestion but to me the problem doesn't seem to be related to X and y shapes. I re-run as following and still have the issue:

```
model.fit_generator(generator=batch_generator(X_train, y_train, divide_on, True), epochs=1,
                                steps_per_epoch=np_steps,
                                verbose=1)
```

```
def batch_generator(X, y, batch_size, shuffle):
    number_of_batches = round(X.shape[0] / batch_size)
    print(f'y.shape: {X.shape}')
    print(f'X.shape[0]: {X.shape[0]}')
    print(f'batch_size: {batch_size}')
    print(f'number_of_batches: {number_of_batches}')
    counter = 0
    sample_index = np.arange(X.shape[0])
    if shuffle:
        np.random.shuffle(sample_index)
    while True:
        batch_index = sample_index[batch_size * counter:batch_size * (counter + 1)]
        print(f'counter: {counter}')
        print(f'batch_index: {batch_index}')
        X_batch = X[batch_index, :].toarray()
        y_batch = y[batch_index]
        counter += 1
        print(f'yielded X_batch shape: {X_batch.shape} where counter: {counter}')
        print(f'yielded y_batch shape: {y_batch.shape} where counter: {counter}')
        yield X_batch, y_batch
        if counter == number_of_batches:
            if shuffle:
                np.random.shuffle(sample_index)
            counter = 0
```
While the result is:

```
shape of x_train: (1407577, 207)
shape of x_valid: (74084, 207)
Epoch 1/1
y.shape: (1407577, 207)
X.shape[0]: 1407577
batch_size: 64
number_of_batches: 21993
counter: 0
batch_index: [  55578  885043  826530 1085983  596906  990879  150577  916018 1283648
  657662   22295  978107 1330422 1094582 1323311 1386819 1349709  361209
 1314015  112607 1363984  179845  464715  474078  337839 1097602 1173681
  910575 1113526   27510  647144 1081263  678677  567365  149537  936813
  202732  727397   21943  563727  923775  661254  465769  383644   99391
  918760 1152295   23548  511531  661704  590537  855781  654484 1008951
  690456  414501  998788   97076  334435   57625  822775  125039  857771
 1103476]
yielded X_batch shape: (64, 207) where counter: 1
yielded y_batch shape: (64, 1) where counter: 1
counter: 1
batch_index: [ 784817  248893  472646 1010253 1400872  522094  217448 1120737  844047
  837030 1298761  768817  728090  799502  951408 1356634  365863  997856
  752368  558098  732175  571739 1048726  536754 1315847 1032336  413975
  366115  550960  976257 1116407  237934  386406 1160910  113013  163694
  437774  372660 1164205  335589  223032 1364559  626345 1135905  396354
 1120329  567954 1252556  763024  351094  445536  734038 1344405  239830
  869035  728995  288278  238975  699285 1267507  131834   24448  233283
  623641]
Traceback (most recent call last):
  File "mlp.py", line 443, in <module>
yielded X_batch shape: (64, 207) where counter: 2
yielded y_batch shape: (64, 1) where counter: 2
    main()
  File "mlp.py", line 371, in main
    model1 = run_model1(X_train, y_train, X_valid, y_valid)
  File "mlp.py", line 255, in run_model1
    verbose=1)
  File "/path_to_project/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/path_to_project/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/path_to_project/venv/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/path_to_project/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 527, in call
    (len(args), len(list(self.signature.input_arg))))
ValueError: Arguments and signature arguments do not match. got: 37, expected: 39 

```

It fails in the second iteration of the loop.

**Comment by ahmedbr** [comment]
> @claeszacho thanks for your suggestion but to me the problem doesn't seem to be related to X and y shapes. I re-run as following and still have the issue:
> 
> ```
> model.fit_generator(generator=batch_generator(X_train, y_train, divide_on, True), epochs=1,
>                                 steps_per_epoch=np_steps,
>                                 verbose=1)
> ```
> 
> ```
> def batch_generator(X, y, batch_size, shuffle):
>     number_of_batches = round(X.shape[0] / batch_size)
>     print(f'y.shape: {X.shape}')
>     print(f'X.shape[0]: {X.shape[0]}')
>     print(f'batch_size: {batch_size}')
>     print(f'number_of_batches: {number_of_batches}')
>     counter = 0
>     sample_index = np.arange(X.shape[0])
>     if shuffle:
>         np.random.shuffle(sample_index)
>     while True:
>         batch_index = sample_index[batch_size * counter:batch_size * (counter + 1)]
>         print(f'counter: {counter}')
>         print(f'batch_index: {batch_index}')
>         X_batch = X[batch_index, :].toarray()
>         y_batch = y[batch_index]
>         counter += 1
>         print(f'yielded X_batch shape: {X_batch.shape} where counter: {counter}')
>         print(f'yielded y_batch shape: {y_batch.shape} where counter: {counter}')
>         yield X_batch, y_batch
>         if counter == number_of_batches:
>             if shuffle:
>                 np.random.shuffle(sample_index)
>             counter = 0
> ```
> 
> While the result is:
> 
> ```
> shape of x_train: (1407577, 207)
> shape of x_valid: (74084, 207)
> Epoch 1/1
> y.shape: (1407577, 207)
> X.shape[0]: 1407577
> batch_size: 64
> number_of_batches: 21993
> counter: 0
> batch_index: [  55578  885043  826530 1085983  596906  990879  150577  916018 1283648
>   657662   22295  978107 1330422 1094582 1323311 1386819 1349709  361209
>  1314015  112607 1363984  179845  464715  474078  337839 1097602 1173681
>   910575 1113526   27510  647144 1081263  678677  567365  149537  936813
>   202732  727397   21943  563727  923775  661254  465769  383644   99391
>   918760 1152295   23548  511531  661704  590537  855781  654484 1008951
>   690456  414501  998788   97076  334435   57625  822775  125039  857771
>  1103476]
> yielded X_batch shape: (64, 207) where counter: 1
> yielded y_batch shape: (64, 1) where counter: 1
> counter: 1
> batch_index: [ 784817  248893  472646 1010253 1400872  522094  217448 1120737  844047
>   837030 1298761  768817  728090  799502  951408 1356634  365863  997856
>   752368  558098  732175  571739 1048726  536754 1315847 1032336  413975
>   366115  550960  976257 1116407  237934  386406 1160910  113013  163694
>   437774  372660 1164205  335589  223032 1364559  626345 1135905  396354
>  1120329  567954 1252556  763024  351094  445536  734038 1344405  239830
>   869035  728995  288278  238975  699285 1267507  131834   24448  233283
>   623641]
> Traceback (most recent call last):
>   File "mlp.py", line 443, in <module>
> yielded X_batch shape: (64, 207) where counter: 2
> yielded y_batch shape: (64, 1) where counter: 2
>     main()
>   File "mlp.py", line 371, in main
>     model1 = run_model1(X_train, y_train, X_valid, y_valid)
>   File "mlp.py", line 255, in run_model1
>     verbose=1)
>   File "/path_to_project/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/path_to_project/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/path_to_project/venv/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
>     reset_metrics=False)
>   File "/path_to_project/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
>     outputs = self.train_function(ins)
>   File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
>     outputs = self._graph_fn(*converted_inputs)
>   File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
>     return self._call_impl(args, kwargs)
>   File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
>     return self._call_flat(args, self.captured_inputs, cancellation_manager)
>   File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
>     ctx, args, cancellation_manager=cancellation_manager))
>   File "/path_to_project/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 527, in call
>     (len(args), len(list(self.signature.input_arg))))
> ValueError: Arguments and signature arguments do not match. got: 37, expected: 39 
> ```
> 
> It fails in the second iteration of the loop.

The problem solved after replacing `import keras` by `import tensorflow.keras` and making the necessary modifications
