### ISSUE TITLE
trying to set a full VGG16 model to trainable = False 

### ISSUE THREAD

**Issue by georgeparry12** [keras-team/keras#13979]
I'm trying to set a VGG16 model so that all of the layers cannot train... but when I do this 

```

	@staticmethod
	def build_object_branch (inputs):

		base_model = VGG16(weights='imagenet', include_top=True, input_shape=(224, 224, 3))(inputs)


		for layer in base_model.layers:
			layer.trainable = False

		model = Model(inputs, base_model)


		return model 

```

I get the error 

```
   for layer in base_model.layers:
AttributeError: 'Tensor' object has no attribute 'layers'
```

I've copied the code from the Keras documentation, however, I wondered if this is due to 1) that I'm using the whole model and not just the top. Or 2) that the VGG16 model is part of a larger network.... but I'm unsure. 

It runs fine if I let the model's layers stay on trainable, but produces this error when I try to change them to untrainable

Any help would be massively appreciated.

**Comment by georgeparry12** [comment]
I fixed it, I was being dumb. this is what I think it should look like

```
		base_model = VGG16(weights='imagenet', include_top=True, input_shape=(224, 224, 3))

		for layer in base_model.layers:
			layer.trainable = False

		x = base_model (inputs)

		model = Model(inputs, x)

		return model
```

**Comment by Saduf2019** [comment]
@georgeparry12 

Moving this issue to closed status as there has been no activity, in case you still face the error please create a new issue.
