### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'best_model.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by moataz-beheta** [keras-team/keras#14074]
Hello
I am trying to build a speech recognition model following this tutorial
[https://www.analyticsvidhya.com/blog/2019/07/learn-build-first-speech-to-text-model-python/](url)
there is 2 part, the first is a training model which output is the input of the second part ( testing model)

at the end of the training model, there is this part which should save the result of the training 
`es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=10, min_delta=0.0001) 
mc = ModelCheckpoint('best_model.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='max')`

so the result should be saved in this file "best_model.hdf5"
this model run without any error but I didn't found any file created

while running the testing model, the model should be loaded using
`model=load_model('best_model.hdf5')`

I got this error message

`/home/moataz/.local/lib/python3.6/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
Using TensorFlow backend.
/home/moataz/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/moataz/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "Model-testing.py", line 10, in <module>
    model=load_model('best_model.hdf5')
  File "/home/moataz/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/moataz/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "/home/moataz/.local/lib/python3.6/site-packages/keras/utils/io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/home/moataz/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/moataz/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'best_model.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

someone can help me ?
I am using Ubuntu 18 as a virtual machine (vmware)

**Comment by AniketSawale** [comment]
I fixed this issue.

Try to give the whole` `path:``
`model=load_model('working_directory_path/best_model.hdf5')`
**Note:** The given path should follow back slash not foward slash.

**Comment by moataz-beheta** [comment]
> #I fixed this issue.
> 
> Try to give the whole` `path:``
> `model=load_model('working_directory_path/best_model.hdf5')`
> **Note:** The given path should follow back slash not foward slash.

thank you for your reply
I tried it but the problem still exist
I think the problem is not in loading the model, it is in saving it because I didn't find any file created after running the model


So I think the problem is here 
`es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=10, min_delta=0.0001)
mc = ModelCheckpoint('best_model.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='max')`

**Comment by AniketSawale** [comment]
Ohh my mistake.
`mc = ModelCheckpoint('working_directory_path/best_model.hdf5',...)`

**Comment by AniketSawale** [comment]
Sorry for my mistake.
Try this:
```
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=10, min_delta=0.0001)

mc = ModelCheckpoint('**path_you_want_to_save**/best_model.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='max')
```

See if this works for you.

**Comment by moataz-beheta** [comment]
> Sorry for my mistake.
> Try this:
> 
> ```
> es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=10, min_delta=0.0001)
> 
> mc = ModelCheckpoint('**path_you_want_to_save**/best_model.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='max')
> ```
> 
> See if this works for you.

still the problem exit
I copied all the traceback
I hope if this help

> Traceback (most recent call last):
>   File "FullModel-tst.py", line 110, in <module>
>     model=load_model('/home/moataz/Desktop/speech/Model/best_model.hdf5')
>   File "/home/moataz/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
>     return load_function(*args, **kwargs)
>   File "/home/moataz/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 583, in load_model
>     with H5Dict(filepath, mode='r') as h5dict:
>   File "/home/moataz/.local/lib/python3.6/site-packages/keras/utils/io_utils.py", line 191, in __init__
>     self.data = h5py.File(path, mode=mode)
>   File "/home/moataz/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
>     swmr=swmr)
>   File "/home/moataz/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 88, in h5py.h5f.open
> OSError: Unable to open file (unable to open file: name = '/home/moataz/Desktop/speech/Model/best_model.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
>

**Comment by itsshavar** [comment]
Check the path once again and check if file is accessible.

**Comment by moataz-beheta** [comment]
> Check the path once again and check if file is accessible.

the problem as I mentioned before that "ModelCheckpoint" doesn't save any file
I didn't found any created file

**Comment by Elpazzu** [comment]
Hi Moataz,

I am having the exact same issue, did you manage to resolve it?

Thanks!
Makram

**Comment by manan15105411262** [comment]
same error
when I run the following code:
"
mode_path = E:/达因风/best/dy_direction_best_cpu.hdf5
model = load_model(model_path) #模型路径
"
an error is here:
OSError: Unable to open file (Unable to open file: name = 'e:/达因风/best/dy_direction_best_cpu.hdf5', errno = -1, error message = 'unknown error', flags = 0, o_flags = 0)
it seems the h5f.open() not support Chinese characters. I try encode the 'model_path' to 'utf-8',but the error still exist. I don't know how to solve it, could you help me ? (keras=2.2.4, h5py=2.6.0, hdf5=1.8.15)
