### ISSUE TITLE
Allow cloning of tf.keras.Model subclass

### ISSUE THREAD

**Issue by jamesbraza** [keras-team/keras#17261]
**System information**.

TensorFlow version (you are using): 2.10.0
Are you willing to contribute it (Yes/No): 

**Describe the feature and the current behavior/state**.

Coming from https://github.com/tensorflow/tensorflow/issues/47048.  Currently, `tf.keras.models.clone_model` does not work with subclasses of `tf.keras.Model`:

```python
class MySequentialModel(tf.keras.Model):
    def __init__(self, name=None, **kwargs):
        super().__init__(**kwargs)
        self.dense_1 = FlexibleDense(out_features=3)
        self.dense_2 = FlexibleDense(out_features=2)

    def call(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)
```

Trying to clone this model via `cloned_model = tf.keras.models.clone_model(model)`

```python
  File "<ipython-input-12-d1c325a8ca03>", line 1, in <module>
    cloned_model = tf.keras.models.clone_model(model)
  File "/path/to/python3.10/site-packages/keras/models/cloning.py", line 505, in clone_model
    return _clone_functional_model(
  File "/path/to/python3.10/site-packages/keras/models/cloning.py", line 173, in _clone_functional_model
    raise ValueError(
ValueError: Expected `model` argument to be a functional `Model` instance, but got a subclassed model instead: <models.core.TransferModel object at 0x103b7bb20>
```

**Will this change the current api? How?**

It will not change the public interface, instead will allow another type to work with `tf.keras.models.clone_model`.  It will instead save developer's time in re-inventing a custom `copy` function for their custom `Model`s.

**Who will benefit from this feature?**

People who want to clone class-based models.

**Comment by qlzh727** [comment]
My understanding is that Keras doesn't have enough information about the subclass model, unless it implements `get_config` and `from_config`. Not sure how this is addressed in the new saving format. @fchollet  and @rchao

**Comment by tilakrayal** [comment]
@jamesbraza,
I tried the mentioned code with the latest tf-nightly v2.13.0-dev20230216 and was able to execute the code without any issues.

```
class MySequentialModel(tf.keras.Model):
    def __init__(self, name=None, **kwargs):
        super().__init__(**kwargs)
        self.dense_1 = FlexibleDense(out_features=3)
        self.dense_2 = FlexibleDense(out_features=2)

    def call(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)
```
Tried to clone this model via **cloned_model = tf.keras.models.clone_model(model)**

Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3b70bf001d7db785b913f6748652e5c2/untitled959.ipynb). Thank you!

**Comment by jamesbraza** [comment]
Hi @tilakrayal thanks for making a Gist, but I am still getting the error with `tensorflow-macos==2.11.0`:

```python
import tensorflow as tf

class SomeModel(tf.keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.dense = tf.keras.layers.Dense(3)

    def call(self, inputs, training=None, mask=None):
        return self.dense(inputs)

test_model = SomeModel()
test_model(tf.ones((1, 42)))
cloned_model = tf.keras.models.clone_model(test_model)
```

Running this:

```python
Traceback (most recent call last):
  File "/path/to/a.py", line 13, in <module>
    cloned_model = tf.keras.models.clone_model(test_model)
  File "/path/to/venv/lib/python3.10/site-packages/keras/models/cloning.py", line 506, in clone_model
    return _clone_functional_model(
  File "/path/to/venv/lib/python3.10/site-packages/keras/models/cloning.py", line 174, in _clone_functional_model
    raise ValueError(
ValueError: Expected `model` argument to be a functional `Model` instance, but got a subclassed model instead: <__main__.SomeModel object at 0x16f32fc40>
```

---

I see you have `tf-nightly v2.13.0-dev20230216`, how can I install that on my macOS Monterey version 12.6?

```bash
> pip install tf-nightly
Looking in indexes: https://pypi.org/simple, https://****/
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly
> pip install tf-nightly==2.13.0-dev20230216
Looking in indexes: https://pypi.org/simple, https://****/
ERROR: Could not find a version that satisfies the requirement tf-nightly==2.13.0-dev20230216 (from versions: none)
ERROR: No matching distribution found for tf-nightly==2.13.0-dev20230216
```

**Comment by tilakrayal** [comment]
@jamesbraza,
**tf-nightly v2.13.0-dev20230216** is not working on MacOS, and for the installation, Your issue seems similar to the issue here https://github.com/tensorflow/tensorflow/issues/58368, could you please close this issue and track the progress in that thread, since it is already involving lots of discussion.
You can follow the instructions here for the M1 mac installations of Tensorflow prebuilt library here https://developer.apple.com/metal/tensorflow-plugin/

And also as mentioned above this cloning issue was resolved in [tf-nightly](https://colab.research.google.com/gist/tilakrayal/3b70bf001d7db785b913f6748652e5c2/untitled959.ipynb) and tf [v2.12.0-rc0](https://colab.research.google.com/gist/tilakrayal/6fd5a292e7f8e028c94d0dc6a4ef730b/untitled976.ipynb) and it will be included in the upcoming tensorflow version. 

I tried on Linux Ubuntu 22.02 also and able to execute the code wihtout any issue/error. Attached the reference

![image](https://user-images.githubusercontent.com/81610181/220272328-dcd77637-5d37-429c-8539-8a0c9a89ac22.png)

**Comment by jamesbraza** [comment]
Thanks for the detailed response!  Unfortunately, I am:
1. Getting no matching distributions from `pip install --pre tensorflow==2.12.0-rc0` on Windows 10 or macOS,
2. Getting build failures when trying to locally build `2.12.0-rc0` tag on Windows 10 (weird LLVM errors) or macOS (hitting https://github.com/tensorflow/tensorflow/issues/58368 that you'd linked above).

I don't want to distract this issue with OS install problems, but I am sad to say that (with both of top two OS's), I am unable to (1) build or (2) `pip install` any of the future tensorflow code.

---

Thus, I can't manually confirm this issued is fixed myself.  Since you're having success @tilakrayal, I trust you.  Feel free to close this issue if you think it's resolved.

**Comment by tilakrayal** [comment]
@jamesbraza,
Thank you for the comment. As mentioned tf-nightly for MacOS will take some more time to publish. So as mentioned, I tried to execute the code on Windows with tensorflow v2.12.rc0(https://github.com/tensorflow/tensorflow/releases)  and it was executed without any issue/error. Kindly find the image for the reference.

![Screenshot (118)](https://user-images.githubusercontent.com/81610181/222740912-7769a4b5-1cbd-4626-806d-67caae01395a.png)
![Screenshot (119)](https://user-images.githubusercontent.com/81610181/222740998-3051c499-e194-404f-b399-523361b38f57.png)

Thank you!

**Comment by jamesbraza** [comment]
Okay sounds good, closing this out! 👍
