### ISSUE TITLE
Default weight naming issue in Keras 3 due to 'backslashing'

### ISSUE THREAD

**Issue by curiarteb** [keras-team/keras#19335]
The following piece of code is only compatible with the SGD optimizer. When using any other keras-type optimizer (such as Adam), the following message appears: 

`ValueError: Argument 'name' must be a string and cannot contain character '/'. Received: name=my_net/kernel_0_momentum`

After checking, the issue seems to be related to an incompatibility of the default naming of the weight-type variables.

Coding specifications:
Python 3.12.2
Keras 3.1.0
Tensorflow 2.16.1

```python
"""
Created on Tue Mar 19 13:37:01 2024

@author: curiarte
"""

import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import tensorflow as tf
import keras
import matplotlib.pyplot as plt
import numpy as np

#keras.config.set_dtype_policy('float64')
keras.backend.set_floatx("float64")
keras.mixed_precision.set_global_policy("float64") 
keras.utils.set_random_seed(1234)

# Data for supervised learning: 
# x_train: 1000 rows, 28 columns, values betweeen -10 and 10 (uniformly distributed).
# y_true: 1000 rows, 2 columns, values betweeen 0 and 1 (uniformly distributed).
x_train = -10 + (10-(-10))*np.random.default_rng().random(size=[1000,28])
y_true = 0 + (1-0)*np.random.default_rng().random(size=[1000,2])

class my_net(keras.Model):
    def __init__(self, penultimate_layer_width, **kwargs):
        super(my_net, self).__init__()
        
        self.penultimate_layer_width = penultimate_layer_width
        
        self.layers_list = list()
        # Hidden layers
        self.layers_list.append(keras.layers.Dense(units=100, activation="tanh", use_bias=True, name="layer1"))
        # self.layers_list.append(keras.layers.Dense(units=100, activation="tanh", use_bias=True))
        # self.layers_list.append(keras.layers.Dense(units=100, activation="tanh", use_bias=True))
        # self.layers_list.append(keras.layers.Dense(units=100, activation="tanh", use_bias=True))
        self.layers_list.append(keras.layers.Dense(units=self.penultimate_layer_width, activation="tanh", use_bias=True, name="penultimatelayer"))
        
        #Last (linear) layer
        self.layers_list.append(keras.layers.Dense(units=2, activation=None, use_bias=False))

    #Model prediction
    def call(self, inputs):

        x = inputs
        for layer in self.layers_list:
            x = layer(x)

        return x
    
class my_model(keras.Model):
    
    def __init__(self, net, **kwargs):
        super(my_model, self).__init__()
        self.net = net
        self.trainable_vars = [v.value for v in self.net.weights]
        self.loss_tracker = keras.metrics.Mean(name="loss")
    
    def call(self, inputs):
        
        x_train, y_true = inputs
        y_pred = self.net(x_train)
        loss = tf.reduce_mean(tf.square(y_pred-y_true))
        return loss
        
    def compile(self, optimizer):
        super().compile()
        self.optimizer = optimizer

    def train_step(self, data):
        
        x_train, y_true = data
        
        with tf.GradientTape(watch_accessed_variables=False) as tape:
            tape.watch(self.trainable_vars)
            loss = self(data)
        
        grad = tape.gradient(loss, self.trainable_vars)
        self.optimizer.apply(grad, self.trainable_vars)
        
        self.loss_tracker.update_state(loss)
        
        return {"loss": self.loss_tracker.result()}

net = my_net(penultimate_layer_width=100)
y_pred = net(x_train) #For building 'net'
model = my_model(net)
model([x_train,y_true]) #For building 'model'

#Compilation (uncomment only one). Working only for SGD.
#model.compile(optimizer=keras.optimizers.SGD())
#model.compile(optimizer=keras.optimizers.RMSprop())
model.compile(optimizer=keras.optimizers.Adam())

history = model.fit(x_train, y_true, epochs=2000, batch_size=200)

#Plos of the loss
plt.plot(history.history["loss"])
plt.yscale("log")
plt.xlabel("Epoch")
plt.title("Loss")
plt.show()
```

**Comment by s-marton** [comment]
Hey there,
I was facing the same problem and found a solution. This might not be the optimal way, but at least it does work for the moment. I changed one line in the ```add_variable_from_reference``` function in ```keras/optimizers/base_optimizer.py``` by adding ```.replace("/", "_")``` to the else block. I still hope the problem will be addressed in an update as I did not check if this change could cause some other problems. Hope this fix helps you as well.

```
    def add_variable_from_reference(
        self, reference_variable, name=None, initializer="zeros"
    ):
        """Add an all-zeros variable with the shape and dtype of a reference
        variable.
        """
        name = name or "var"
        if hasattr(reference_variable, "path"):
            name = reference_variable.path.replace("/", "_") + "_" + name
        else:
            name = str(reference_variable.name).replace(":", "_").replace("/", "_") + "_" + name
        return self.add_variable(
            shape=reference_variable.shape,
            initializer=initializer,
            dtype=reference_variable.dtype,
            name=name,
        )
```

**Comment by curiarteb** [comment]
Thank you very much! 

Hopefully this bug will be fixed soon by the Keras team.

**Comment by yongqiangzhangzazzle** [comment]
Hi there, just wondering if anyone from Keras team has started working on this issue?

**Comment by andremfreitas** [comment]
Hi, 
I have the same problem only with ADAM (not SGD for example as the OP).
I am using: tf 2.16.1 and python 3.10.

**Comment by fchollet** [comment]
Thanks for the report -- I fixed the issue at HEAD.

**Comment by sachinprasadhs** [comment]
Reference commit: https://github.com/keras-team/keras/commit/c5e939d4e5e4b4e53f71b98a58439fbd54cea4b8

**Comment by tomaz-suller** [comment]
Is anyone else also experiencing this issue still? I'm on Python 3.9.19 using Keras 3.3.3.

Trying to use the PyTorch backend since it provides better tooling for exporting models to ONNX later on.

The code I have now is just
```python
import os
os.environ["KERAS_BACKEND"] = "torch"
import keras

print(keras.__version__)  # '3.3.3'

fnn = keras.Sequential(
    keras.layers.Input(shape=(50,)),
    keras.layers.Dense(25),
    keras.layers.Dense(2),
)
fnn.compile()
```
which gives me `ValueError: Argument ``name`` must be a string and cannot contain character ``/``. Received: name=<Dense name=dense_3, built=False> (of type <class 'keras.src.layers.core.dense.Dense'>)`

<details>
<summary>Full traceback</summary>
<br>
<pre>
<code>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 1
----> 1 fnn = keras.Sequential(
      2     keras.layers.Input(shape=(50,)),
      3     keras.layers.Dense(25),
      4     keras.layers.Dense(2),
      5 )
      6 fnn.compile()

File ~/venv/lib/python3.9/site-packages/keras/src/models/sequential.py:68, in Sequential.__init__(self, layers, trainable, name)
     67 def __init__(self, layers=None, trainable=True, name=None):
---> 68     super().__init__(trainable=trainable, name=name)
     69     self._functional = None
     70     self._layers = []

File ~/venv/lib/python3.9/site-packages/keras/src/models/model.py:156, in Model.__init__(self, *args, **kwargs)
    154     functional.Functional.__init__(self, *args, **kwargs)
    155 else:
--> 156     Layer.__init__(self, *args, **kwargs)

File ~/venv/lib/python3.9/site-packages/keras/src/layers/layer.py:247, in Layer.__init__(self, activity_regularizer, trainable, dtype, autocast, name, **kwargs)
    245 BackendLayer.__init__(self)
    246 self._lock = False
--> 247 Operation.__init__(self, dtype=dtype, name=name)
    248 self.activity_regularizer = regularizers.get(activity_regularizer)
    249 input_dim_arg = kwargs.pop(\"input_dim\", None)

File ~/venv/lib/python3.9/site-packages/keras/src/ops/operation.py:21, in Operation.__init__(self, dtype, name)
     19     name = auto_name(self.__class__.__name__)
     20 if not isinstance(name, str) or \"/\" in name:
---> 21     raise ValueError(
     22         \"Argument `name` must be a string and \"
     23         \"cannot contain character `/`. \"
     24         f\"Received: name={name} (of type {type(name)})\"
     25     )
     26 self._dtype_policy = dtype_policies.get(dtype)
     27 self.name = name

ValueError: Argument `name` must be a string and cannot contain character `/`. Received: name=<Dense name=dense_5, built=False> (of type <class 'keras.src.layers.core.dense.Dense'>)"
</code>
</pre>
</details>

**Comment by bjourne** [comment]
Isn't the problem that Keras rejects names containing slashes? As such names are regularly created by ONNX it makes importing ONNX-models into Keras difficult.
