### ISSUE TITLE
bug in TF _keepdims?

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19630]
I think this should be `x.shape[i]`, not `tf.shape[i]`: https://github.com/keras-team/keras/blob/0f3bd5222bb46ac6da3ed96187e7ec908aa851fa/keras/src/backend/tensorflow/numpy.py#L759

**Comment by fchollet** [comment]
Good catch -- this is now fixed & tested at HEAD.

**Comment by jonbarron** [comment]
Looks like _keepdims() is still broken, did a PR slip through the cracks?

**Comment by jonbarron** [comment]
Hmm sorry never mind, I think I'm mistaken.
