### ISSUE TITLE
Will Keras 3 support intel gpu with oneapi

### ISSUE THREAD

**Issue by HaroldYin1024** [keras-team/keras#20497]
Dear Keras Team,

The latest version of [pytorch 2.5](https://pytorch.org/blog/pytorch2-5/) already supports Intel GPU. Users can use pytorch on Intel GPU with [minimum code change.](https://pytorch.org/docs/main/notes/get_start_xpu.html). 

```
# CUDA CODE
tensor = torch.tensor([1.0, 2.0]).to("cuda")

# CODE for Intel GPU
tensor = torch.tensor([1.0, 2.0]).to("xpu")
```

Will Keras team follow up to support [Intel OneAPI](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html) ecosystem? Thank you very much!

**Comment by fchollet** [comment]
Then Keras with the PyTorch backend should already be working with the XPU device, right? Did you try it?

In general Keras only executes computation via a backend, so support for new devices would happen at the level of the backend not at the level of Keras itself. Keras code is agnostic to CPU/GPU/TPU/etc aside from automated device placement and device count related logic (in the distribution API).

**Comment by HaroldYin1024** [comment]
> Then Keras with the PyTorch backend should already be working with the XPU device, right? Did you try it?
> 
> In general Keras only executes computation via a backend, so support for new devices would happen at the level of the backend not at the level of Keras itself. Keras code is agnostic to CPU/GPU/TPU/etc aside from automated device placement and device count related logic (in the distribution API).

I see. I didn't find it in the document, so I thought it wasn't supported. Thank you for the information, and I will try it later.

**Comment by HaroldYin1024** [comment]
> Then Keras with the PyTorch backend should already be working with the XPU device, right? Did you try it?
> 
> In general Keras only executes computation via a backend, so support for new devices would happen at the level of the backend not at the level of Keras itself. Keras code is agnostic to CPU/GPU/TPU/etc aside from automated device placement and device count related logic (in the distribution API).

Dear @fchollet 
I have tried training MNIST with Keras 3.0 using Torch as the backend, but the Intel GPU is not utilized during the training. The issue remains.
I can confirm that I have installed all the prerequisites for PyTorch on Intel XPU, and I can successfully use PyTorch to train MNIST with the GPU. So I guess the problem is on keras's side.

**Comment by HaroldYin1024** [comment]
@fchollet 

I have tested by editing the source code in /keras/src/backend/torch/core.py. I replaced all the "cuda" with "xpu". Then, intel GPU was successfully utilized during my training.

My pytorch version is 2.5. In this latest version, pytorch provide a new function [torch.xpu.is_available](https://pytorch.org/docs/stable/generated/torch.xpu.is_available.html).

Just want to provide keras team with the information, and hope there will be a permanent solution implemented in later version. Thanks.

**Comment by fchollet** [comment]
@HaroldYin1024 we can modify the backend so as to set the XPU as default device if it is available. We already do this for the MPS device on macs. Do you see potential cases where one would have both XPU and CUDA available at the same time?

**Comment by fchollet** [comment]
@HaroldYin1024 I have made this change so you can try to install Keras at HEAD and see if that works for you.

**Comment by HaroldYin1024** [comment]
> @HaroldYin1024 I have made this change so you can try to install Keras at HEAD and see if that works for you.

@fchollet It works for me! Thank you!
