### ISSUE TITLE
Undefined output shape in Conv2DTranspose

### ISSUE THREAD

**Issue by divamgupta** [keras-team/keras#6777]
If we use keras with tensorflow, the output shape of a Conv2DTranspose is undefined even if the input shape is fixed. This problem doesn't happen with Conv2D . This is probably due to a bug in the implementation of   Conv2DTranspose.

```
import tensorflow as tf

config = tf.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)

from keras.layers.convolutional import Conv2DTranspose , Conv2D

layer1 = Conv2DTranspose( 8  , (4 , 4) , strides=(1, 1)  , data_format='channels_first'  , input_shape=(3,64,64) )
layer2 = Conv2D( 8 , (4, 4) , strides=(1, 1), input_shape=(3, 64, 64) , data_format='channels_first'  )

BATCH_SIZE = 32
x = tf.placeholder(tf.float32, shape=( BATCH_SIZE , 3, 64 , 64 ))
          
o1 = layer1( x )
o2 = layer2( x )


print o1.get_shape() # Prints (?, 8, ?, ?) , why???
print o2.get_shape() # Prints (32, 8, 61, 61) , which is correct 
```

**Comment by lukasbrunke** [comment]
I encountered the same issue! I had to use the following to determine the output shape:
`shape_o1 = layer1.compute_output_shape(input_shape)`

**Comment by divamgupta** [comment]
Yes, There is a bug in the implementation on this layer. This is causing other source codes to break.

**Comment by b03902043** [comment]
I add this line ```print (inputs, input_shape) ``` at convolutional.py
the output : 
```
(<tf.Tensor 'activation_9/Relu:0' shape=(?, 64, 64, 256) dtype=float32>, <tf.Tensor 'conv2d_transpose_1/Shape:0' shape=(4,) dtype=int32>)
```

It seems that ```K.shape(line 742) ```cannot get the exact shape of input tensor...

**Comment by divamgupta** [comment]
Any updates on this issue?

**Comment by zach-nervana** [comment]
I have also run into this bug. It requires some ugly workarounds. any updates?

**Comment by Dobiasd** [comment]
I too encoutered this bug.

The following code
```python
from keras.models import Model
from keras.layers import Input, Conv2D, Conv2DTranspose
from keras import backend as K

assert K.image_data_format() == 'channels_last'

inp = Input(shape=(((32, 32, 3))))
out_1 = Conv2D(8, (3, 3), strides=(1, 1), padding='same')(inp)
out_2 = Conv2DTranspose(8, (3, 3), strides=(1, 1), padding='same')(inp)

print(out_1.shape)
print(out_2.shape)
```
produces this output (Keras Version 2.0.8, TensorFlow 1.3.0)
```
(?, 32, 32, 8)
(?, ?, ?, 8)
```
To me it looks like it is caused by [this TensorFlow bug](https://github.com/tensorflow/tensorflow/issues/8972).

**Comment by Dobiasd** [comment]
Just as an update: It still happens with Keras 2.1.1 and TensorFlow 1.4.0. I will check again with the next release of a new TensorFlow version.

**Comment by gdubrg** [comment]
I can check the output shape with `_keras_shape` property of the layer.

**Comment by AnudeepKonda** [comment]
A nasty workaround is to explicitly mention the output shape.  
<your_tensor>.set_shape(<output_shape>)

**Comment by Dobiasd** [comment]
@gdubrg Thanks. Accessing a protected member is not perfect, but it works for [my purpose](https://github.com/Dobiasd/frugally-deep).

**Comment by marioviti** [comment]
Kudos @gdubrg

**Comment by mrlzla** [comment]
I have faced the problem too

**Comment by FiReTiTi** [comment]
Same problem for me :-(
Any better workaround?

**Comment by Dobiasd** [comment]
Changing the imports to the Keras version included in Tensorflow also fixed the problem:

```python
from tensorflow.python import keras
from tensorflow.python.keras.layers import Input, Conv2D, Conv2DTranspose
from tensorflow.python.keras import backend as K

assert K.image_data_format() == 'channels_last'

inp = Input(shape=(((32, 32, 3))))
out_1 = Conv2D(8, (3, 3), strides=(1, 1), padding='same')(inp)
out_2 = Conv2DTranspose(8, (3, 3), strides=(1, 1), padding='same')(inp)

print(out_1.shape)
print(out_2.shape)
```
```
(?, 32, 32, 8)
(?, 32, 32, 8)
```

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by kwaegel** [comment]
@wt-huang Is this really resolved? It seems like the solution above is "abandon Keras and use tf.keras", which isn't ideal.

**Comment by min050820** [comment]
@wt-huang This isn't solved! Keras from TF and vanilla keras is not compatible. A project should use either tf.keras or just keras and not both. Changing the whole project to use tf.keras is a huge job.

**Comment by Dobiasd** [comment]
I also don't like it, but the [notes of the latest vanilla Keras release](https://github.com/keras-team/keras/releases/tag/2.3.0) even state:

> This is also the last major release of multi-backend Keras. Going forward, we recommend that users consider switching their Keras code to tf.keras in TensorFlow 2.0. It implements the same Keras 2.3.0 API (so switching should be as easy as changing the Keras import statements), but it has many advantages for TensorFlow users, such as support for eager execution, distribution, TPU training, and generally far better integration between low-level TensorFlow and high-level concepts like Layer and Model. It is also better maintained.
> Development will focus on tf.keras going forward. We will keep maintaining multi-backend Keras over the next 6 months, but we will only be merging bug fixes. API changes will not be ported.

:cry:

**Comment by kwaegel** [comment]
I suppose that's that, then. Still pretty annoying since, a) TF 2.0 is still in beta, and b) tf.keras is _not_ a drop-in replacement, as evidenced by the week or so of work I had to put in switching over to get around this bug.

(The latter point may now be true with the 2.3.0 update, but I think that also points towards the high volatility in machine learning libraries.)

**Comment by davideboschetto** [comment]
My latest pull request fixed this issue: #13778
